config/routes.rb
Rails.application.routes.draw do
  post '/result', to: 'papers#index'
  root 'papers#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/alternatives/elixir_way.rb
class PapersController < ApplicationController
  def search; end

  def index
    @from = params[:from] || 2010
    @to = params[:to] || 2018
    @profiles = params[:profiles].split(/\r\n/)

    @papers = @profiles
    |> fetch_papers_for_each_profile
    |> flatten_papers
    |> papers_with_uniqe_title
    |> remove_profile_and_person
    |> append_points
    |> sort_by_points

    @papers = sorted_papers
    @score = sum_paper_points(@papers)
  end

  private

  def filter_profiles_by_names(names)
    Profile.where(name: names)
  end

  def fetch_papers_for_each_profile(profiles)
    profiles.map { |profile| papers(profile.name, @from, @to) }
  end

  def flatten_papers(papers_for_each_profile)
    papers_for_each_profile.flatten
  end

  def papers_with_uniqe_title(papers)
    papers.uniq { |paper| paper["title"] }
  end

  def remove_profile_and_person(papers)
    papers.map { |paper| paper.except("profile", "person") }
  end

  def append_points(papers)
    papers.map { |paper| paper.merge("points" => points(paper["journal"], paper["year"])) }
  end

  def sort_by_points(papers)
    papers.sort_by { |paper| paper["points"] }.reverse
  end

  def sum_paper_points(papers)
    papers.sum { |paper| paper["points"] }
  end

  def papers(profile, from, to)
    PapersService.new.call(profile, from, to)
  end

  def points(journal, year)
    PointsService.new.call(journal, year)
  end
end

app/controllers/alternatives/lambda_way.rb
class PapersController < ApplicationController
  def search; end

  def index
    @from = params[:from] || 2010
    @to = params[:to] || 2018
    @profiles = params[:profiles].split(/\r\n/)

    @papers = Profile.
      where(name: @profiles).
      map { |profile| papers(profile.name, @from, @to) }.
      flatten.
      map { |paper| paper.except("profile", "person") }.
      uniq { |paper| paper["title"] }.
      map { |paper| paper.merge("points" => points(paper["journal"], paper["year"])) }.
      sort_by { |paper| paper["points"] }.
      reverse

    @score = @papers.sum { |paper| paper["points"] }
  end

  private

  def papers(profile, from, to)
    PapersService.new.call(profile, from, to)
  end

  def points(journal, year)
    PointsService.new.call(journal, year)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  def search; end

  def index
    @from = params[:from] || 2010
    @to = params[:to] || 2018
    @profiles = params[:profiles].split(/\r\n/)

    @papers = Profile.
      where(name: @profiles).
      map { |profile| papers(profile.name, @from, @to) }.
      flatten.
      map { |paper| paper.except("profile", "person") }.
      uniq { |paper| paper["title"] }.
      map { |paper| paper.merge("points" => points(paper["journal"], paper["year"])) }.
      sort_by { |paper| paper["points"] }.
      reverse

    @score = @papers.sum { |paper| paper["points"] }
  end

  private

  def papers(profile, from, to)
    PapersService.new.call(profile, from, to)
  end

  def points(journal, year)
    PointsService.new.call(journal, year)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
.container
  %nav.navbar.navbar-dark.bg-inverse
    %ul.nav.navbar-nav.clearfix
      %li.nav-item
        %button.navbar-toggler.hidden-sm-up.nav-link{"aria-controls" => "exCollapsingNavbar2", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#exCollapsingNavbar2", "data-toggle" => "collapse", :type => "button"}
          \ &#9776;
    #exCollapsingNavbar2.collapse.navbar-toggleable-xs
      = link_to "Rails bootstrap", root_path, class: 'navbar-brand'
      %ul.nav.navbar-nav= render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Google Scholar'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Google Scholar'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/papers/index.html.haml
%h1 Scholar+ (from #{@from} to #{@to})
%h3 for profiles: #{@profiles.to_sentence}

%table.table
  %thead
    %tr
      %th #
      - @papers.first.keys.each do |attribute|
        %th= attribute.humanize
  %tbody
    - @papers.each_with_index do |paper, index|
      %tr
        %th= index + 1
        - paper.each do |_, value|
          %td= value

%p Score: <b>#{@score}</b>

app/views/papers/search.html.haml
%h1 Scholar+
%h3 Calculate points

= form_tag(result_path) do |form|
  %div.form-group
    = label_tag 'from', 'From'
    = number_field_tag 'from', 2010, class: 'from-control'
    %div.form-group
    = label_tag 'to', 'To'
    = number_field_tag 'to', 2018, class: 'from-control'
  %div.form-group
    = label_tag 'profiles', 'Profiles to involve in the calculation'
    = text_area_tag 'profiles', 'michal', class: 'form-control', rows: 6
  %div.form-group
    = button_tag 'Calculate', class: 'btn btn-primary'